CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users
(
    uid BIGSERIAL PRIMARY KEY,
    uuid uuid DEFAULT uuid_generate_v4() NOT NULL CONSTRAINT uni_users_uuid UNIQUE,
    username TEXT NOT NULL CONSTRAINT uni_users_username UNIQUE,
    password TEXT NOT NULL,
    ROLE TEXT DEFAULT 'user'::TEXT NOT NULL
);

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
