CREATE TABLE users
(
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role     VARCHAR(255),
    username VARCHAR(255) NOT NULL CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE,
    uuid     uuid         NOT NULL CONSTRAINT uk6km2m9i3vjuy36rnvkgj1l61s UNIQUE
);

ALTER TABLE users OWNER TO main;

